git:
  depth: 10

language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - '8'
  - '7'
  - '6'

script:
  - npm test

after_success:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
