git:
  depth: 10

language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '8'
  - '10'

env:
  - DEST=/tmp

before_install:
  - npm install -g pm2
  - npm install
  - npm run bootstrap

before_script:
  - pm2 ping

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
